animals/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('shelter.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

shelter/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^animals/$', views.AnimalListView.as_view(), name='animals'),
    url(r'^animal/(?P<pk>\d+)$', views.AnimalDetailView.as_view(), name='animal-detail'),
    url(r'^shelter/(?P<pk>\d+)$', views.ShelterDetailView.as_view(),
        name='shelter-detail'),
    url(r'^animal/create/$', views.AnimalCreate.as_view(), name='animal_create'),
    url(r'^animal/(?P<pk>\d+)/update/$', views.AnimalUpdate.as_view(),
        name='animal_update'),
    url(r'^animal/(?P<pk>\d+)/delete/$', views.AnimalDelete.as_view(),
        name='animal_delete'),
    url(r'^shelter/create/$', views.ShelterCreate.as_view(), name='shelter_create'),
]

shelter/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse


class Animal(models.Model):
    """Model representing animal in a shelter."""
    name = models.CharField(max_length=200, help_text="Enter a animal name.")
    age = models.IntegerField(help_text="Enter a animal age (integer).")
    date_of_arrival = models.DateField(help_text="Enter a date of arrival (yyyy-mm-dd).")
    weight = models.FloatField(help_text="Enter a animal weight.")
    height = models.FloatField(help_text="Enter a animal height.")
    special_signs = models.CharField(
        max_length=200,
        help_text="Enter a animal special signs"
    )
    shelter = models.ForeignKey('Shelter', on_delete=models.SET_NULL, null=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular shelter instance.
        """
        return reverse('animal-detail', args=[str(self.id)])

    def __str__(self) -> str:
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Shelter(models.Model):
    """Model representing shelter."""
    name = models.CharField(max_length=200, help_text="Enter a shelter name")

    def get_absolute_url(self):
        """
        Returns the url to access a particular shelter instance.
        """
        return reverse('shelter-detail', args=[str(self.id)])

    def __str__(self) -> str:
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    shelter = models.ForeignKey('Shelter', on_delete=models.SET_NULL, null=True)
    role = models.IntegerField(default=0)

    @property
    def is_admin(self) -> bool:
        return self.role == 2

    @property
    def is_user(self) -> bool:
        return self.role == 1

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Client.objects.create(user=instance)
        instance.client.save()

    def __str__(self) -> str:
        """String for representing the Model object (in Admin site etc.)"""
        return self.user.username

shelter/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from shelter.models import Shelter, Animal


@login_required
def index(request):
    shelter_list = Shelter.objects.all()

    return render(
        request,
        'index.html',
        context={
            'shelter_list': shelter_list,
        }
    )


class AnimalListView(generic.ListView):
    model = Animal
    paginate_by = 10

    def get_queryset(self):
        return Animal.objects.all()

    def get_context_data(self, **kwargs):
        context = super(AnimalListView, self).get_context_data(**kwargs)
        return context


class AnimalDetailView(generic.DetailView):
    model = Animal


class ShelterDetailView(generic.DetailView):
    model = Shelter


class AnimalCreate(CreateView):
    model = Animal
    fields = '__all__'


class AnimalUpdate(UpdateView):
    model = Animal
    fields = '__all__'


class AnimalDelete(DeleteView):
    model = Animal
    success_url = reverse_lazy('animals')


class ShelterCreate(CreateView):
    model = Shelter
    fields = '__all__'

shelter/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                <ul class="sidebar-nav">
                    {% if user.is_authenticated %}
                        <li>User: {{ user.get_username }}</li>
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'animals' %}">All pets</a></li>
                        <li>
                            <a href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
                        </li>
                    {% else %}
                        <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">
            {% block content %}{% endblock %}
            {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
                    </div>
                {% endif %}
            {% endblock %}
        </div>
    </div>

</div>
</body>
</html>

shelter/templates/index.html
{% extends "base_generic.html" %}

{% block title %}<title>Shelter Home</title>{% endblock %}

{% block content %}
    <h1>Shelter Home</h1>

    <p>Welcome to <em>Shelter</em>, a website with different shelters.</p>

    <p>This website works with these shelters.</p>
    {% if shelter_list %}
        <ul>

            {% for shelter in shelter_list %}
                <li><a href="{{ shelter.get_absolute_url }}">{{ shelter }}</a></li>
            {% endfor %}
        </ul>

        {% if user.client.is_admin %}
            <a href="{% url 'shelter_create' %}"> Create Shelter</a>
        {% endif %}
    {% else %}
        <p>There are no authors available.</p>
        {% if user.client.is_admin %}
            <a href="{% url 'shelter_create' %}"> Create Shelter</a>
        {% endif %}
    {% endif %}

{% endblock %}

shelter/templates/shelter/animal_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Animal</h1>

<p>Are you sure you want to delete the animal: {{ animal.name }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

shelter/templates/shelter/animal_detail.html
{% extends "base_generic.html" %}

{% block content %}
    {% if user.is_authenticated %}

        <h1>Name: {{ animal.name }}</h1>

        <p><strong>Shelter:</strong> <a
                href="{{ animal.shelter.get_absolute_url }}">{{ animal.shelter }}</a>
        </p>
        <p><strong>Age:</strong> {{ animal.age }}</p>
        <p><strong>Date of arrival:</strong> {{ animal.date_of_arrival }}</p>
        <p><strong>Weight:</strong> {{ animal.weight }}</p>
        <p><strong>Height:</strong> {{ animal.height }}</p>
        <p><strong>Special Signs:</strong> {{ animal.special_signs }}</p>


        {% if user.client.is_admin %}
            <div><a href="{% url 'animal_update' animal.pk %}">Upgrade
                Animal</a></div>
            <div><a href="{% url 'animal_delete' animal.pk %}">Delete
                Animal</a></div>
        {% endif %}

        {% if user.client.is_user %}
            <div><a href="{% url 'animal_update' animal.pk %}">Upgrade
                Animal</a></div>
        {% endif %}
    {% else %}
        <h1>Please log in</h1>
    {% endif %}
{% endblock %}

shelter/templates/shelter/animal_form.html
{% extends "base_generic.html" %}
{% load bootstrap %}

{% block content %}

<form action="" method="post" role="form">
    <legend>Animal</legend>
    {% csrf_token %}
    {{ form|bootstrap }}
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    
</form>
{% endblock %}

shelter/templates/shelter/animal_list.html
{% extends "base_generic.html" %}

{% block content %}

    {% if user.is_authenticated %}
        <h1>Animal List</h1>

        {% if animal_list %}

            <table class="table table-hover">
                <tr>
                    <th>Name</th>
                    <th>Shelter</th>

                    {% if user.client.is_admin %}
                        <th>Upgrade</th>
                        <th>Delete</th>
                    {% endif %}

                    {% if user.client.is_user %}
                        <th>Upgrade</th>
                    {% endif %}

                </tr>
                {% for animal in animal_list %}
                    <tr>
                        <td>
                            <div>
                                <a href="{{ animal.get_absolute_url }}">{{ animal.name }}</a>
                            </div>
                        </td>
                        <td>
                            <div><a href="{{ animal.shelter.get_absolute_url }}">
                                {{ animal.shelter }}</a></div>
                        </td>
                        {% if user.client.is_admin %}
                            <td>
                                <div><a href="{% url 'animal_update' animal.pk %}">Upgrade
                                    Animal</a></div>
                            </td>
                            <td>
                                <div><a href="{% url 'animal_delete' animal.pk %}">Delete
                                    Animal</a></div>
                            </td>
                        {% endif %}

                        {% if user.client.is_user %}
                            <td>
                                <div><a href="{% url 'animal_update' animal.pk %}">Upgrade
                                    Animal</a></div>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </table>

            {% if user.client.is_admin or user.client.is_user %}
                <hr/>
                <ul class="sidebar-nav">
                    <li><a href="{% url 'animal_create' %}">Create Animal</a></li>
                </ul>
            {% endif %}

        {% else %}
            <p>There are no animals in the shelters.</p>
        {% endif %}

    {% else %}
        <h1>Please log in</h1>
    {% endif %}
{% endblock %}

shelter/templates/shelter/shelter_detail.html
{% extends "base_generic.html" %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Shelter: {{ shelter }}</h1>

        <h4>Animals</h4>

        <table class="table table-hover">
            <tr>
                <th>Name</th>
                <th>Special Signs</th>
            </tr>
            {% for animal in shelter.animal_set.all %}
                <tr>
                    <td>
                        <div><a href="{{ animal.get_absolute_url }}">{{ animal.name }}</a>
                        </div>
                    </td>
                    <td>
                        <div>{{ animal.special_signs }}</div>
                    </td>
                </tr>
            {% endfor %}
        </table>

        {% if user.client.is_admin or user.client.is_user %}
            <hr/>
            <ul class="sidebar-nav">
                <li><a href="{% url 'animal_create' %}">Create Animal</a></li>
            </ul>
        {% endif %}
    {% else %}
        <h1>Please log in</h1>
    {% endif %}
{% endblock %}

shelter/templates/shelter/shelter_form.html
{% extends "base_generic.html" %}
{% load bootstrap %}

{% block content %}

<form action="" method="post" role="form">
    <legend>Shelter</legend>
    {% csrf_token %}
    {{ form|bootstrap }}
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    
</form>
{% endblock %}